reportbug/submit.py: use message_from_binary_file to attach messages
In Python3 we can no longer use `email.message_from_file()` to read
message files opened in binary mode. According to the documentation, we
should switch to `email.message_from_binary_file()`.

Fixes:

    Traceback (most recent call last):
      File "/usr/bin/reportbug", line 2302, in <module>
        main()
      File "/usr/bin/reportbug", line 1107, in main
        return iface.user_interface()
      File "/usr/bin/reportbug", line 2286, in user_interface
        submit.send_report(
      File "/usr/lib/python3/dist-packages/reportbug/submit.py", line 227, in send_report
        (message, failed) = mime_attach(body, attachments, charset, body_charset)
      File "/usr/lib/python3/dist-packages/reportbug/submit.py", line 179, in mime_attach
        part = MIMEMessage(email.message_from_file(fp),
      File "/usr/lib/python3.8/email/__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "/usr/lib/python3.8/email/parser.py", line 56, in parse
        feedparser.feed(data)
      File "/usr/lib/python3.8/email/feedparser.py", line 175, in feed
        self._input.push(data)
      File "/usr/lib/python3.8/email/feedparser.py", line 103, in push
        self._partial.write(data)
    TypeError: string argument expected, got 'bytes'

Closes: #966480