reportbug/ui/gtk_ui.py: fix crash with Python 3.9
The deprecated `isAlive()` alias to `threading.Thread.is_alive()` has
been removed in Python 3.9. This leads to a crash in reportbug when
trying to show the bug log of an existing report:

  File "/usr/lib/python3/dist-packages/reportbug/ui/gtk_ui.py", line 435, in pulse
    return self.isAlive()
AttributeError: 'BugPage' object has no attribute 'isAlive'

The fix is to switch to the correct method.

Closes: #975398