bin/reportbug: Fix crash in offer_configuration
Even we don't need to ask for smtptls if the user specifies port 465, we
still need to set the local variable. Add the missing else clause.

Fixes:

    Traceback (most recent call last):
      File "/usr/bin/reportbug", line 2302, in <module>
        main()
      File "/usr/bin/reportbug", line 1107, in main
        return iface.user_interface()
      File "/usr/bin/reportbug", line 1225, in user_interface
        offer_configuration(self.options)
      File "/usr/bin/reportbug", line 709, in offer_configuration
        if smtptls:
    UnboundLocalError: local variable 'smtptls' referenced before assignment

Closes: #965977