reportbug/utils.py: fix get_source_name
commit 18e9472f4d5e9851ab35b030e799ecd59318c6dd changed get_source_name
to reliably find the correct source package, but unintentionally also
changed behavior for the case where the passed package name only matches
a source package and no binary packages. This could result in a crash:

    Traceback (most recent call last):
      File "/usr/bin/reportbug", line 2302, in <module>
        main()
      File "/usr/bin/reportbug", line 1107, in main
        return iface.user_interface()
      File "/usr/bin/reportbug", line 1476, in user_interface
        prompt='Select one of these packages: ')
      File "/usr/lib/python3/dist-packages/reportbug/ui/text_ui.py", line 356, in menu
        maxlen_name = min(max(list(map(len, allowed))), columns // 3)
    TypeError: object of type 'NoneType' has no len()

Fix it.